{% set name = "psqlODBC" %}
{% set version = "17_00_0007" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/postgresql-interfaces/psqlodbc/archive/refs/tags/REL-{{ version|replace('.','_') }}.tar.gz
  sha256: cf15619e7fcc31ce3f61634243ca9fbb1e1c7dfdac19d7bda2a66483c029d4b5

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python
    - make
    - autoconf
    - automake
    - libtool
  host:
    - unixodbc 2.3.11
    - postgresql 17.6
    - libpq {{ libpq }}
  run:
    - unixodbc
    - libpq

test:
  requires:
    - conda-build
  commands:
    - conda inspect linkages psqlodbc
    # This is using .so on both osx and linux
    - test -f $PREFIX/lib/psqlodbca.so  # [unix]
    - test -f $PREFIX/lib/psqlodbcw.so  # [unix]

about:
  home: https://odbc.postgresql.org/
  license: LGPL-2.0
  license_family: GPL
  license_file: license.txt
  summary: psqlODBC is the official PostgreSQL ODBC Driver
  description: |
    A library to talk to the PostgreSQL DBMS using ODBC.
  doc_url: https://odbc.postgresql.org/
  dev_url: https://github.com/postgresql-interfaces/psqlodbc/

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
