{% set name = 'psqlODBC' %}
{% set version = "13.01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: 'https://ftp.postgresql.org/pub/odbc/versions/src/psqlodbc-{{ version }}.0000.tar.gz'
  sha256: 435de2ea38109b8384ed76d327032b73a53a915379a752a34b0f9c7539055da7

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - python >=3.6
    - make   # [not win]
    - m2-make   # [win]
  host:
    - unixodbc
    - postgresql
  run:
    - unixodbc
    - libpq

test:
  commands:
    - conda inspect linkages psqlodbc
    # This is using .so on both osx and linux
    - test -f $PREFIX/lib/psqlodbca.so  # [unix]
    - test -f $PREFIX/lib/psqlodbcw.so  # [unix]

about:
  home: https://odbc.postgresql.org/
  license: LGPL-2.0
  license_family: GPL
  license_file: license.txt
  summary: psqlODBC is the official PostgreSQL ODBC Driver
  doc_url: https://odbc.postgresql.org/
  dev_url: https://git.postgresql.org/gitweb/?p=psqlodbc.git

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
