travis:
  secure:
    BINSTAR_TOKEN: XaZh8E4iTs1WhUZqbzTqSOTrFCtH4uDtzU1P6EQz8qobJNBRQYu4vH7nehTx+Grf4dZylK1EkRxEiktoBgl4pCDzdHPPdeKeqf589fDMsUbxS9+gSsnRYCctSw4SiEzYlf0n74qD9FH/3+ZNCgsLy1KBJRdoFwLhlJklIJafP0YX5l9LD77xQ7E6yN3SpSphxrr5zEqkZCRb+ePYfBq1HseyaiOx/YQWReoDsv+95EJ2uKqcOLbtmqFZcUpTdEDcYc7LCW0I0evxU1HBp7/q608v50Bion02aXE8yyL0LYrsuQ7V36+msKoBDjvN4meH092LI+/nVwZpL4tHbtAatUqopzLK/N2Abic2q8MBxzd9qpVrgMwQPbWMCm6czmjbXTm4Tp8Yzt84xiwQUQdQQZOdNIj4/+EP++1uBOFnQsuAipvT5gHXvIaT0JtefHOaLWfuDMEB7p5pnWW9MUKwuMT0SGI6Oifu9Pv4c4K3Fe/ahXeVDddgmlHCTRBT+9vDc/ihb/c3C7ooXkBTUXhxhLDWsYUCwRALcUxqXAjidMvePWPbLIQhdl0PwJR6McCqJ2+x+Gu+2+hsDVvf4paJmB/9+FeBouf4W2YvZUhTHkGGb7BvI6xip9bvzR9aPYHMwnt1qj4SfXs+dSBflR9cPuuTpTsvEdAqU29+JbAdubU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
